# Generated by Django 5.1.4 on 2025-12-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at']},
        ),
    ]
