# Generated by Django 5.1.4 on 2025-01-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Estimated duration in days', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
