# Generated by Django 5.1.4 on 2026-01-06 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_comment'),
        ('teams', '0003_alter_team_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_company',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], db_index=True, default='To Do', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', 'status'], name='projects_pr_team_id_4a0091_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client_company'], name='projects_pr_client__dda03b_idx'),
        ),
    ]
