# Generated by Django 5.1.4 on 2025-01-29 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=datetime.datetime(2025, 1, 29, 14, 3, 55, 793720, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
