"""
Django settings for swifthub project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []

# DEBUG = os.environ.get("DEBUG", "True") == "True"
DEBUG = os.environ.get("DEBUG", "False") == "True"

# ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Nolasi hostus no vides mainīgā (ko padod GitHub Actions)
raw_hosts = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost")
ALLOWED_HOSTS = [h.strip() for h in raw_hosts.split(",") if h.strip()]

# Obligāti Cloudflare/Proxy gadījumā
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Dinamiski CSRF iestatījumi (Aizstāj izdzēsto bloku)
CSRF_TRUSTED_ORIGINS = []
for host in ALLOWED_HOSTS:
    CSRF_TRUSTED_ORIGINS.append(f"https://{host}")
    CSRF_TRUSTED_ORIGINS.append(f"http://{host}")
    # Pievienojam arī variantu ar portu 82, jo Nginx to izmanto ārpusē
    CSRF_TRUSTED_ORIGINS.append(f"http://{host}:82")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party apps
    'tempus_dominus',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_celery_beat',
    'phonenumber_field',
    'django_recaptcha',

    # custom apps
    'accounts',
    'projects',
    'tasks',
    'notifications',
    'teams',
    'comments'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.auth.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'swifthub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notification_context',
                'accounts.context_processors.recaptcha_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'swifthub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# --------------------------
# Datubāze
# --------------------------

# Pārbaudām, vai esam Docker vidē (skatāmies vai ir DB_NAME)
if os.environ.get("DB_NAME"):
    # Docker / Production (Postgres)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("DB_PASS"),
            "HOST": os.environ.get("DB_HOST", "postgresdb"),
            "PORT": os.environ.get("DB_PORT", 5432),
        }
    }
else:
    # Lokāli uz datora (SQLite)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# if os.environ.get("DEBUG") == "True":
#     # Lokāli SQLite
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.sqlite3",
#             "NAME": BASE_DIR / "db.sqlite3",
#         }
#     }
# else:
#     # Docker / production
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": os.environ.get("DB_NAME"),
#             "USER": os.environ.get("DB_USER"),   # šeit jābūt projectuser
#             "PASSWORD": os.environ.get("DB_PASS"),
#             "HOST": os.environ.get("DB_HOST", "postgresdb"),
#             "PORT": os.environ.get("DB_PORT", 5432),
#         }
#     }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'lv'

LANGUAGES = [
    ('en', 'English'),
    ('lv', 'Latvian')
]

TIME_ZONE = 'Europe/Riga'

USE_I18N = True

USE_TZ = True

# Pievieno savu lokālo adresi un portu
# CSRF_TRUSTED_ORIGINS = [
#     'http://127.0.0.1:82',
#     'http://localhost:82',
#     'http://projekti.test.lv'
# ]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# settings.py
STATIC_URL = '/static/'

# Šai mapei ir jāsakrīt ar ceļu 'web' servisā iekš docker-compose
STATIC_ROOT = '/static/' 

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# URL, ko redzēs pārlūkprogrammā (piem., /media/bildes/foto.jpg)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Absolūtais ceļš konteinerā, kur faili tiks saglabāti
# Tāpat kā static, mēs gribam tos likt pašā saknē, lai vieglāk mapot Volume
# MEDIA_ROOT = '/media/'

if DEBUG:
    CELERY_TASK_ALWAYS_EAGER = True
else:
    CELERY_TASK_ALWAYS_EAGER = False # Ļauj strādāt Redis/Celery strādniekam

# CRISPY FORM TEMPLATE TAGS
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# celery configuration options

REDIS_HOST = os.environ.get("REDIS_HOST")
REDIS_PORT = os.environ.get("REDIS_PORT")

if REDIS_HOST and REDIS_PORT:
    CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
    CELERY_RESULT_BACKEND = CELERY_BROKER_URL
else:
    CELERY_BROKER_URL = None
    CELERY_RESULT_BACKEND = None
    
# if os.environ.get("REDIS_HOST") and os.environ.get("REDIS_PORT"):
# CELERY_BROKER_URL = f"redis://{os.environ.get('REDIS_HOST')}:{os.environ.get('REDIS_PORT')}/0"

# CELERY_RESULT_BACKEND = CELERY_BROKER_URL
# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Europe/Riga'

# django celery beat scheduler
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

# Fake Celery (ja negribi mainīt kodu)
# CELERY_TASK_ALWAYS_EAGER = True
# CELERY_TASK_EAGER_PROPAGATES = True


# custom django auth settings
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = LOGIN_URL

# Ielādējam atslēgas no .env
RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY')

# # TESTA VIDEI (kad DEBUG ir True)
# if os.getenv('DEBUG') == 'True':
#     # Šis mainīgais pasaka django-recaptcha neiet uz Google serveriem, 
#     # bet vienmēr atgriezt "True" validāciju.
#     os.environ['RECAPTCHA_TESTING'] = 'True'

    
#     # Ja .env failā nav atslēgu, iestatām testa atslēgas, lai sistēma neizmet kļūdu
#     if not RECAPTCHA_PUBLIC_KEY:
#         RECAPTCHA_PUBLIC_KEY = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
#         RECAPTCHA_PRIVATE_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'

# # Produkcijas pārbaude
# if not RECAPTCHA_PUBLIC_KEY and os.getenv('DEBUG') != 'True':
#     print("WARNING: RECAPTCHA_PUBLIC_KEY is missing in Production!")

if DEBUG:
    os.environ['RECAPTCHA_TESTING'] = 'True'
    if not RECAPTCHA_PUBLIC_KEY:
        RECAPTCHA_PUBLIC_KEY = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
        RECAPTCHA_PRIVATE_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'
else:
    # Produkcijā TESTĒŠANAI JĀBŪT FALSE
    os.environ['RECAPTCHA_TESTING'] = 'False'

# Iestatījumi
RECAPTCHA_REQUIRED_SCORE = 0.5
RECAPTCHA_LANGUAGE = 'lv'
RECAPTCHA_USE_SSL = False

# Izmanto tieši šo nosaukumu, ko rāda kļūda:
SILENCED_SYSTEM_CHECKS = ['django_recaptcha.recaptcha_test_key_error']


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#E pasts:

# Pārbauda, vai lietot e-pastu pa īstam vai tikai izvadīt konsolē
# if os.getenv('DEBUG') == 'True':
#     # Izstrādes laikā: izvada e-pastu terminālī, nesūtot nekur
#     EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# else:
#     # Produkcijā: izmanto reālo SMTP
#     EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# if DEBUG:  # Izmanto jau definēto Boolean mainīgo
#     EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# else:
#     EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL') == 'True'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)