"""
Django settings for swifthub project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=d3ttsmjat4wyixx*@3ks^@ja$o_%6b%#_o56$6!7nn871-_k8'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# DEBUG=False

# ALLOWED_HOSTS = []

DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party apps
    'tempus_dominus',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_celery_beat',
    'phonenumber_field',
    'django_recaptcha',

    # custom apps
    'accounts',
    'projects',
    'tasks',
    'notifications',
    'teams',
    'comments'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.auth.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'swifthub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'swifthub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# --------------------------
# Datubāze
# --------------------------
if os.environ.get("DEBUG") == "True":
    # Lokāli SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Docker / production
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),   # šeit jābūt projectuser
            "PASSWORD": os.environ.get("DB_PASS"),
            "HOST": os.environ.get("DB_HOST", "postgresdb"),
            "PORT": os.environ.get("DB_PORT", 5432),
        }
    }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'lv'

LANGUAGES = [
    ('en', 'English'),
    ('lv', 'Latvian')
]

TIME_ZONE = 'Europe/Riga'

USE_I18N = True

USE_TZ = True

# Pievieno savu lokālo adresi un portu
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:82',
    'http://localhost:82',
    'http://projekti.test.lv'
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# settings.py
STATIC_URL = '/static/'

# Šai mapei ir jāsakrīt ar ceļu 'web' servisā iekš docker-compose
STATIC_ROOT = '/static/' 

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# URL, ko redzēs pārlūkprogrammā (piem., /media/bildes/foto.jpg)
MEDIA_URL = '/media/'

# Absolūtais ceļš konteinerā, kur faili tiks saglabāti
# Tāpat kā static, mēs gribam tos likt pašā saknē, lai vieglāk mapot Volume
MEDIA_ROOT = '/media/'

# CRISPY FORM TEMPLATE TAGS
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# celery configuration options

REDIS_HOST = os.environ.get("REDIS_HOST")
REDIS_PORT = os.environ.get("REDIS_PORT")

if REDIS_HOST and REDIS_PORT:
    CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
    CELERY_RESULT_BACKEND = CELERY_BROKER_URL
else:
    CELERY_BROKER_URL = None
    CELERY_RESULT_BACKEND = None
    
# if os.environ.get("REDIS_HOST") and os.environ.get("REDIS_PORT"):
# CELERY_BROKER_URL = f"redis://{os.environ.get('REDIS_HOST')}:{os.environ.get('REDIS_PORT')}/0"

# CELERY_RESULT_BACKEND = CELERY_BROKER_URL
# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'Europe/Riga'

# django celery beat scheduler
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

# Fake Celery (ja negribi mainīt kodu)
# CELERY_TASK_ALWAYS_EAGER = True
# CELERY_TASK_EAGER_PROPAGATES = True


# custom django auth settings
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = LOGIN_URL

# Tagad piešķiram vērtības no vidi (os.getenv)
RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY')

# Ieteicams: Pievieno pārbaudi, lai izvairītos no kļūdām, ja mainīgie pazūd
if not RECAPTCHA_PUBLIC_KEY:
    print("Warning: RECAPTCHA_PUBLIC_KEY is not set!")

RECAPTCHA_REQUIRED_SCORE = 0.6
RECAPTCHA_USE_SSL = False
RECAPTCHA_LANGUAGE = 'lv'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
