# Generated by Django 5.1.4 on 2025-01-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notifaction_notifiction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifiction',
            options={'ordering': ['-created_at']},
        ),
    ]
