# Generated by Django 5.1.4 on 2025-01-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notifiction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifiction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
